### ISSUE TITLE
关于需求文档中用例逻辑的问题

### ISSUE THREAD

**Issue by wenguang1998** [buaaembeddedse/shattuckite-doc#46]
在创建用例的过程中，发现**管理设备**用例显得有些多余，如下图
![example](https://user-images.githubusercontent.com/44225816/59090964-d40c5100-8940-11e9-8ac8-f768d0ed539c.png)
以及case.json中对**管理设备**的描述：
`{ "name": "管理设备",
    "user": ["普通用户"],
    "scene":[
      "管理设备包含的操作：\n",
      "1. 管理传感器\n",
      "用户可以在本页面选择操作类型",
      "管理设备页面拥有返回至主页面的按钮。"
    ],
    "prerequisites":["概览系统情况"],
    "exception": [],
    "mobileGUI":[
      {
        "pageName":"manage",
        "subPage":[
          {
            "pageName":"manageDevice",
            "subPage":["manageDevice_detail"]
          }
        ]
      }
    ]
  }`
个人感觉这一部分显得很没有必要，现在主要有两个想法：
1、将**操作执行器**添加到**管理设备**中去
2、将**管理设备**这个节点删除
请做一个定夺，谢谢 @CNLHC

**Comment by CNLHC** [comment]
可以。请按想法1进行修改，将操作执行器移动到管理设备这个用例中去。

**Comment by CNLHC** [comment]
如无其他异议请关闭issue
